# arch -x86_64 pod install --repo-update

name: goals_lite
description: Goals lite is a simple tool that helps you manage your goals.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.6+6

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sign_in_with_apple: ^3.3.0
  modal_bottom_sheet: ^2.0.0
  charts_flutter: ^0.12.0

  # firebase
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.6
  shared_preferences: ^2.0.11
  intl: ^0.17.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  hive_generator: ^1.1.2
  cupertino_tabbar: ^2.0.0
  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  build_runner: ^2.1.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/

  fonts:
    - family: Jalnan
      fonts:
        - asset: assets/fonts/Jalnan.ttf

